server:
  port: ${PORT:1111}

spring:
  application:
    name: message-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  eureka:
    enabled: true

---
spring:
  profiles: local

ribbon:
  eureka:
    enabled: false

greeting-service:
  ribbon:
    listOfServers: localhost:2222

celebrity-service:
  ribbon:
    listOfServers: localhost:3333

---
spring:
  profiles: stub

ribbon:
  eureka:
    enabled: false

greeting-service:
  ribbon:
    listOfServers: localhost:8500

celebrity-service:
  ribbon:
    listOfServers: localhost:8500