server:
  port: ${applicationServerPort}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaHost}:${eurekaPort}/eureka/

# Application Custom Properties
security:
  publicKey:
    filename: ${securityPublicKeyFilename}
