spring:
  datasource:
    url: jdbc:postgresql://localhost/celebrity_service
    username: cs_user
    password: cs_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  enabled: true

# custom configs
security:
  publicKey:
    filename: pubkey