server:
  port: ${applicationServerPort:3333}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaHost:localhost}:${eurekaPort:8761}/eureka/

spring:
  datasource:
    url: jdbc:postgresql://${dbHost:localhost}/celebrity_service
    username: ${dbPass:cs_user}
    password: ${dbPass:cs_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

liquibase:
  enabled: false

# Application Custom Properties
security:
  publicKey:
    filename: ${securityPublicKeyFilename:pubkey}
