spring:
  datasource:
    url: jdbc:postgresql://localhost/greeting_service?currentSchema=greeting
    username: gs_user
    password: gs_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db_changelog_master.xml