spring:
  datasource:
    url: jdbc:postgresql://localhost/message_service?currentSchema=gs
    username: gs_user2
    password: gs_pass2
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db_changelog_master.xml
  url: jdbc:postgresql://localhost/message_service?currentSchema=gs
  user: gs_user1
  password: gs_pass1