server:
  port: ${applicationServerPort}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaHost}:${eurekaPort}/eureka/

# Application Custom Properties
security:
  keystore:
    alias: ${securityKeystoreAlias}
    filename: ${securityKeystoreFilename}
    passphrase: ${securityKeystorePassphrase}

oauth2:
  clientId: ${oauth2ClientId}
  clientSecret: ${oauth2ClientSecret}
  scope: ${oauth2Scope}